spring.application.name=demo
spring.datasource.url=jdbc:mysql://localhost:3306/sqa_social
spring.datasource.username=root
spring.datasource.password=Teste@1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
